version: '3.6'
services:
  hasura:
    image: hasura/graphql-engine:v2.0.0-beta.1
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_SERVER_PORT}/${POSTGRES_TARGET_DB}?sslmode=require
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}   
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_LOG_LEVEL: "debug"
    command:
    - graphql-engine
    - serve
  caddy:
    image: caddy:2.3.0
    depends_on:
    - hasura
    restart: always
    environment:
    - "CADDY_SITE_ADDRESS=${CADDY_SITE_ADDRESS}"   
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
volumes:
  caddy_data:
  caddy_config: